### ISSUE TITLE
Consider moving elm-css and node-elm-compiler to peerDependencies

### ISSUE THREAD

**Issue by halfzebra** [tcoopman/elm-css-webpack-loader#15]
I don't have a strong opinion on that, but I guess it would be a reasonable change, so users can control the versions.

@tcoopman what do you think about that?

**Comment by tcoopman** [comment]
I'm willing to change this is these are the current best practices

**Comment by halfzebra** [comment]
Closing this due to the lack of interest 🙂 

Have a nice day!
